# Generated by Django 3.2.9 on 2021-11-04 01:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacoes',
            fields=[
                ('id_avaliacao', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=255)),
                ('id_author', models.IntegerField()),
                ('id_artista', models.IntegerField()),
            ],
        ),
    ]
