# Generated by Django 3.2.9 on 2021-11-04 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacoes',
            name='classificao',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
