from .serializers import AvaliacoesSerializer
from .models import Avaliacoes
from rest_framework.response import Response
from rest_framework.views import APIView
from rest_framework import status
import nltk

nltk.download('stopwords')
nltk.download('rslp')



class AvaliacoesAPIView(APIView):

    def post(self, request):
        # Classificando a avaliação 
        classificacao = AvaliacoesAPIView.classifica(request.data['descricao'])
        # Guardando a avaliação já classficada
        serializer = AvaliacoesSerializer(data={

            "descricao": request.data['descricao'],
            "classificao": classificacao,
            "id_author":  request.data['id_author'],
            "id_artista": request.data['id_artista']
        }

        )
        serializer.is_valid(raise_exception=True)
        serializer.save()
        return Response(serializer.data, status.HTTP_201_CREATED)

    def get(self, request):

        avaliacoes = Avaliacoes.objects.all()
        serializer = AvaliacoesSerializer(avaliacoes, many=True)
        return Response(serializer.data)

    def classifica(avaliacao):
        # Base de dados para treinamento:
        basetreinamento = [
            ('este trabalho e agradável', 'alegria'),
            ('gosto de ficar no seu aconchego', 'alegria'),
            ('fiz a ades„o ao curso hoje', 'alegria'),
            ('eu sou admirada por muitos', 'alegria'),
            ('adoro como voce e', 'alegria'),
            ('adoro', 'alegria'),
            ('adoro a cor dos seus olhos', 'alegria'),
            ('somo ao amaveis um com o outro', 'alegria'),
            ('sinto uma grande afeicaoo por ele', 'alegria'),
            ('quero agradar meus filhos', 'alegria'),
            ('me sinto completamente amado', 'alegria'),
            ('eu amo voce', 'alegria'),
            ('que grande alivio', 'alegria'),
            ('a dor esta amenizando finalmente', 'alegria'),
            ('acho que me apaixonei', 'alegria'),
            ('amar e maravilhoso', 'alegria'),
            ('estou me sentindo muito animada', 'alegria'),
            ('me sinto muito bem hoje', 'alegria'),
            ('como o luar e belo', 'alegria'),
            ('o dia esta muito bonito', 'alegria'),
            ('nossa como sou afortunado', 'alegria'),
            ('as maravilhas do mundo', 'alegria'),
            ('recebi muito carinho hoje do meus colegas', 'alegria'),
            ('estou me sentindo reconfortada hoje', 'alegria'),
            ('e muito bom estar com os amigos', 'alegria'),
            ('estou muito contente com o resultado dos testes', 'alegria'),
            ('essa pintura esta bem brilhante', 'alegria'),
            ('temos agua em abundancia', 'alegria'),
            ('que roupa delicada', 'alegria'),
            ('voce e um grande comediante', 'alegria'),
            ('que bondade a sua em vir aqui', 'alegria'),
            ('o amor e lindo', 'alegria'),
            ('nossa amizade vai durar para sempre', 'alegria'),
            ('estou eufórica com a noticia', 'alegria'),
            ('ele e realmente fiel a mim', 'alegria'),
            ('vou dar uma grande festa para comemorar meu aniversario', 'alegria'),
            ('gracas a deus que eu enxerguei o certo', 'alegria'),
            ('essa e a melhor escolhas de todas', 'alegria'),
            ('o mais incrÌvel e vocÍ minha bela', 'alegria'),
            ('e t„o engraÁado tentar explicar', 'alegria'),
            ('e emocionante estar neste lugar', 'alegria'),
            ('estou cativada pelo seu olhar', 'alegria'),
            ('estou loucamente apaixonada', 'alegria'),
            ('eu nunca tive duvidas', 'alegria'),
            ('estou rodeada pelo seu abraÁo', 'alegria'),
            ('eu vejo estrelas pelo caminho', 'alegria'),
            ('eu sinto o sol sempre que vocÍ esta por perto', 'alegria'),
            ('eu estou sorrindo de orelha a orelha', 'alegria'),
            ('isso vale a pena', 'alegria'),
            ('finalmente vocÍ colocou meu amor em primeiro lugar', 'alegria'),
            ('nÛs danÁamos noite adentro', 'alegria'),
            ('seu amor e brilhante', 'alegria'),
            ('toquei muitos coraÁıes durante o meu caminho', 'alegria'),
            ('eu serei sua amiga e companheira', 'alegria'),
            ('vocÍ me traz de volta a vida', 'alegria'),
            ('vocÍ e como um sonho doce', 'alegria'),
            ('adoro este doce de frutas', 'alegria'),
            ('meu suco favorito', 'alegria'),
            ('estou agradecida pela ajuda', 'alegria'),
            ('e um enorme prazer ter vocÍ em nossa equipe', 'alegria'),
            ('trabalhar em equipe e o melhor', 'alegria'),
            ('me sinto flutuando no ar', 'alegria'),
            ('a brisa esta agrad·vel hoje', 'alegria'),
            ('Ûtimo e compatÌvel', 'alegria'),
            ('somos compatÌveis um com o outro', 'alegria'),
            ('o Ûrg„o e compatÌvel com o paciente', 'alegria'),
            ('estou contente fui aceita na faculdade', 'alegria'),
            ('fui aprovada no meu exame', 'alegria'),
            ('fui beneficiada pela minha empresa', 'alegria'),
            ('eu sou muito cativante', 'alegria'),
            ('estou contente com o apoio', 'alegria'),
            ('como este lugar e confort·vel', 'alegria'),
            ('e bom estar quente neste frio', 'alegria'),
            ('um elogio nunca e demais', 'alegria'),
            ('vou te chamar para comemorar', 'alegria'),
            ('e desej·vel a sua presenÁa em nossa apresentaÁ„o', 'alegria'),
            ('sou muito grata a vocÍ', 'alegria'),
            ('me dedico muito naquilo que faÁo', 'alegria'),
            ('estou completamente apaixonada ', 'alegria'),
            ('vamos agitar essa noite ', 'alegria'),
            ('vocÍ significa muito para mim', 'alegria'),
            ('vamos agir sem preconceitos e julgamentos', 'alegria'),
            ('finalmente completei a minha coleÁ„o, maravilhoso', 'alegria'),
            ('eu sou sua rainha ', 'alegria'),
            ('satisfatoriamente eu anuncio o vencedor dos jogos', 'alegria'),
            ('vocÍ me atrai facilmente ', 'alegria'),
            ('aquele rapaz e extremamente atraente', 'alegria'),
            ('sinto-me viva ', 'alegria'),
            ('sinto-me em paz ', 'alegria'),
            ('estamos tendo muito lucro', 'alegria'),
            ('muito bem esta tudo em ordem agora ', 'alegria'),
            ('podemos arrumar um emprego juntos ', 'alegria'),
            ('a arrumaÁ„o esta terminada, que alÌvio', 'alegria'),
            ('o cancer e benigno ', 'alegria'),
            ('o amor e abundante', 'alegria'),
            ('vamos ser caridosos este natal', 'alegria'),
            ('com todo esse charme vocÍ ir· atrair a todos', 'alegria'),
            ('nossa como vocÍ e charmoso querido ', 'alegria'),
            ('sou querida pelos meu amigos', 'alegria'),
            ('seja cuidadoso com os meus sentimentos', 'alegria'),
            ('estou comovido com tamanha caridade', 'alegria'),
            ('um ch· quente e reconfortante', 'alegria'),
            ('que alegria ter vocÍs aqui ', 'alegria'),
            ('vamos aplaudir o vencedor ', 'alegria'),
            ('palmas para a aniversariante', 'alegria'),
            ('desejo a vocÍ tudo de bom', 'alegria'),
            ('hora de apreciar um bom vinho', 'alegria'),
            ('aprecio sua presenÁa em minha escola', 'alegria'),
            ('anseio por seus prÛximos trabalhos', 'alegria'),
            ('maravilhoso jogo amistoso', 'alegria'),
            ('e Ûtimo que os ‚nimos tenham se apaziguado', 'alegria'),
            ('concretizei finalmente meu sonho', 'alegria'),

            ('vocÍ e abomin·vel', 'desgosto'),
            ('abomino a maneira como vocÍ age', 'desgosto'),
            ('estou adoentado', 'desgosto'),
            ('meu pai esta adoentado', 'desgosto'),
            ('estamos todos doentes', 'desgosto'),
            ('essa situaÁ„o e muito amarga', 'desgosto'),
            ('disse adeus amargamente', 'desgosto'),
            ('tenho antipatia por aquela pessoa', 'desgosto'),
            ('como pode ser t„o antip·tica!', 'desgosto'),
            ('que horrÌvel seu asqueroso', 'desgosto'),
            ('tenho avers„o agente como vocÍ', 'desgosto'),
            ('isso tudo e sÛ chateaÁ„o', 'desgosto'),
            ('estou muito chateada com suas mentiras', 'desgosto'),
            ('t„o desagrad·vel', 'desgosto'),
            ('isso me desagrada completamente', 'desgosto'),
            ('te desagrada isso', 'desgosto'),
            ('estou com enjÙos terrÌveis', 'desgosto'),
            ('todos est„o enfermos', 'desgosto'),
            ('foi uma enfermidade terrÌvel', 'desgosto'),
            ('isso e muito grave', 'desgosto'),
            ('n„o seja t„o grosseiro', 'desgosto'),
            ('vocÍ fez uma manobra ilegal', 'desgosto'),
            ('sua indecente, n„o tem vergonha?', 'desgosto'),
            ('vocÍ e malvado com as crianÁas', 'desgosto'),
            ('que coment·rio maldoso', 'desgosto'),
            ('sem escr˙pulos vocÍ manipula a tudo', 'desgosto'),
            ('sinto repulsa por vocÍ', 'desgosto'),
            ('e repulsivo a maneira como olha para as pessoas', 'desgosto'),
            ('estou indisposta', 'desgosto'),
            ('a indisposiÁ„o me atacou hoje', 'desgosto'),
            ('acho que vou vomitar', 'desgosto'),
            ('tem muito vomito l·', 'desgosto'),
            ('que incomodo essa dor', 'desgosto'),
            ('n„o me incomode nunca mais', 'desgosto'),
            ('suas bobagens est„o nos incomodando', 'desgosto'),
            ('que nojo olha toda essa sujeira', 'desgosto'),
            ('como isso est· sujo', 'desgosto'),
            ('tenho n·useas sÛ de lembrar', 'desgosto'),
            ('me sinto nauseada com o cheiro desta comida', 'desgosto'),
            ('vocÍ esta obstruindo a passagem de ar', 'desgosto'),
            ('vocÍ esta terrivelmente doente', 'desgosto'),
            ('olhe que feia esta roupa', 'desgosto'),
            ('que atitude deplor·vel', 'desgosto'),
            ('nossa como vocÍ e feio', 'desgosto'),
            ('muito mau tudo isso', 'desgosto'),
            ('estou desgostoso com vocÍ', 'desgosto'),
            ('vocÍ cortou o meu assunto', 'desgosto'),
            ('para que tanta chateaÁ„o?', 'desgosto'),
            ('esse perfume e enjoativo', 'desgosto'),
            ('ser perigoso n„o nada bom', 'desgosto'),
            ('vocÍ e perigoso demais para minha filhas', 'desgosto'),
            ('que fetido este esgoto', 'desgosto'),
            ('que fedido vocÍ esta', 'desgosto'),
            ('que cachorro malcheiroso', 'desgosto'),
            ('hora que ultraje', 'desgosto'),
            ('e ultrajante da sua parte', 'desgosto'),
            ('situaÁ„o desagrad·vel essa', 'desgosto'),
            ('vocÍ sÛ me da desgosto', 'desgosto'),
            ('tenho avers„o a pessoas assim', 'desgosto'),
            ('antipatia e um mal da sociedade', 'desgosto'),
            ('que criatura abomin·vel', 'desgosto'),
            ('e depressiva a maneira como vocÍ vÍ o mundo', 'desgosto'),
            ('me desagrada sua presenÁa na festa', 'desgosto'),
            ('sinto asco dessa coisa', 'desgosto'),
            ('que hediondo!', 'desgosto'),
            ('vou golfar o cafe fora', 'desgosto'),
            ('hora que garota detest·vel!', 'desgosto'),
            ('estou nauseada', 'desgosto'),
            ('isso que vocÍ disse foi muito grave', 'desgosto'),
            ('n„o seja obsceno na frente das crianÁas', 'desgosto'),
            ('n„o seja rude com as visitas', 'desgosto'),
            ('esse assunto me da repulsa', 'desgosto'),
            ('que crianÁa terrivelmente travessa', 'desgosto'),
            ('que crianÁa mal educada', 'desgosto'),
            ('estou indisposta te dar o divorcio', 'desgosto'),
            ('t„o patetico, n„o tem nada mais rude para dizer?', 'desgosto'),
            ('por motivo torpe, com emprego de meio cruel e com impossibilidade de defesa para a vÌtima', 'desgosto'),
            ('a inveja e t„o vil e vergonhosa que ninguem se atreve a confess·-la', 'desgosto'),
            ('o miser·vel receio de ser sentimental e o mais vil de todos os receios modernos', 'desgosto'),
            ('travesso gato quando fica com saudades do dono mija no sapato', 'desgosto'),
            ('isso e um ato detest·vel e covarde', 'desgosto'),
            ('revelam apenas o que e destrutivo e detest·vel para o povo', 'desgosto'),
            ('n„o sei como e a vida de um patife, mais a de um homem honesto e abomin·vel', 'desgosto'),
            ('h· coisas que temos que suportar para n„o acharmos a vida insuport·vel', 'desgosto'),
            ('as injurias do tempo e as injustiÁas do homem', 'desgosto'),
            ('odioso e desumano', 'desgosto'),
            ('vocÍ n„o publicar· conte˙do odiento, pornogr·fico ou ameaÁador', 'desgosto'),
            ('rancoroso e reprimido', 'desgosto'),
            ('n„o h· animal mais degradante, est˙pido, covarde, lament·vel, egoÌsta, rancoroso e invejoso do que o homem', 'desgosto'),
            ('o virulento debate ente polÌticos', 'desgosto'),

            ('eu imploro, n„o me matem!', 'medo'),
            ('tem certeza que n„o e perigoso?', 'medo'),
            ('n„o tenho certeza se e seguro', 'medo'),
            ('tenho que correr pra n„o me pegarem', 'medo'),
            ('socorro! ele queria roubar os meus doces!', 'medo'),
            ('esse cara est· me perseguindo', 'medo'),
            ('n„o entro l·, e um lugar muito perigoso', 'medo'),
            ('este lugar continua assustador', 'medo'),
            ('na selva tem muitos animais perigosos', 'medo'),
            ('avancem com cautela', 'medo'),
            ('este lugar est· silencioso de mais, cuidado!', 'medo'),
            ('por favor, deixe-me viver!', 'medo'),
            ('vou ficar sem mesada se tirar nota baixa', 'medo'),
            ('parece que tem olhos nos vigiando', 'medo'),
            ('eu temo que a sentenÁa do juiz possa ser negativa', 'medo'),
            ('mas essa miss„o e arriscada', 'medo'),
            ('salvem-se quem puder!', 'medo'),
            ('meu plano pode ser descoberto', 'medo'),
            ('n„o tive culpa, juro n„o fui eu', 'medo'),
            ('tenho que tomar cuidado com o lobisomem', 'medo'),
            ('se eu n„o achar, ele vai descobrir a verdade', 'medo'),
            ('meu deus, ele desapareceu!', 'medo'),
            ('tomara que eles n„o me vejam daqui!', 'medo'),
            ('mantenha isso em segredo, se descobrirem estaremos ferrados', 'medo'),
            ('por favor, me soltem, eu sou inocente', 'medo'),
            ('estou ouvindo passos atr·s de mim', 'medo'),
            ('eu vou pedir socorro!', 'medo'),
            ('cuidado com as curvas na estrada', 'medo'),
            ('n„o sei n„o, parece perigoso', 'medo'),
            ('estou tremendo de medo!', 'medo'),
            ('socorro, eu vou cair!', 'medo'),
            ('eu n„o vou ate a floresta negra, e muito perigoso', 'medo'),
            ('ouÁo passos na minha direÁ„o', 'medo'),
            ('acho que est· arriscado de mais', 'medo'),
            ('vamos voltar, e muito perigoso', 'medo'),
            ('fuja, se n„o acabaremos mortos', 'medo'),
            ('receio por n„o me livrar desta situaÁ„o', 'medo'),
            ('socorro! ele est· armado!', 'medo'),
            ('ei cuidado, vocÍ vai bater no poste!', 'medo'),
            ('socorro, nÛs estamos afundando', 'medo'),
            ('e serio, cuidado com essa arma!', 'medo'),
            ('os tubarıes est„o atacando!', 'medo'),
            ('sinto arrepios quando fico sozinho no escuro', 'medo'),
            ('calma, eu n„o estou com o dinheiro', 'medo'),
            ('eu acho que estou sendo enganado', 'medo'),
            ('ligeiro, temos que fugir depressa', 'medo'),
            ('tem um crocodilo selvagem vindo para c·', 'medo'),
            ('se ficarmos quietos eles n„o v„o nos achar', 'medo'),
            ('fuja! o tigre parece faminto', 'medo'),
            ('estou sem saÌda, preciso de um milagre', 'medo'),
            ('tire isso de mim! socorro!', 'medo'),
            ('n„o sei nadar, vou me afogar!', 'medo'),
            ('n„o tenho certeza se e seguro', 'medo'),
            ('vou apanhar se meus pais verem meu boletim', 'medo'),
            ('n„o consigo sair daqui!', 'medo'),
            ('se sair t„o tarde, poderei ser assaltada', 'medo'),
            ('n„o me deixe por favor!', 'medo'),
            ('espere, n„o pode me largar aqui sozinho', 'medo'),
            ('temo pela sua seguranÁa', 'medo'),
            ('eu te entrego o dinheiro, por favor n„o me mate!', 'medo'),
            ('ele vai levar todo o meu dinheiro', 'medo'),
            ('n„o dirija t„o r·pido assim', 'medo'),
            ('me descobriram, ir„o me prender!', 'medo'),
            ('sÛ espero que n„o me faÁam nenhum mal', 'medo'),
            ('vou me afogar, me ajudem a sair da ·gua', 'medo'),
            ('n„o estaremos a salvo aqui', 'medo'),
            ('n„o quero nem pensar no que pode acontecer', 'medo'),
            ('nessa cidade e uma desgraÁa atr·s da outra', 'medo'),
            ('alguem esta me ligando, estou assustado', 'medo'),
            ('isso n„o e remedio, n„o me matem', 'medo'),
            ('eu n„o confio nele, tenho que ter cautela', 'medo'),
            ('muita cautela', 'medo'),
            ('vou ser descoberto, meu deus', 'medo'),
            ('receio que terei de ir', 'medo'),
            ('a noite e muito perigosa', 'medo'),
            ('estou estremecendo com essa casa', 'medo'),
            ('olha aquela criatura se movendo monstruosamente', 'medo'),
            ('n„o ag¸ento este suspense', 'medo'),
            ('afugente os c„es', 'medo'),
            ('estou chocado e amedrontado com este assassinato brutal', 'medo'),
            ('e preciso afugenta com Ìmpeto este medo do inferno', 'medo'),
            ('seu polÌticos usam suas forÁas para afugentar e amedrontar o povo', 'medo'),
            ('o objetivo disso e apenas me amedrontar mais', 'medo'),
            ('isso me apavora', 'medo'),

            ('ele a feriu profundamente', 'raiva'),
            ('vou despejar minha cÛlera em vocÍ', 'raiva'),
            ('me sinto atormentado', 'raiva'),
            ('n„o me contrarie', 'raiva'),
            ('vou destruir tudo  que foi construÌdo', 'raiva'),
            ('n„o consigo terminar este trabalho, e muito frustrante', 'raiva'),
            ('me frustra a sua presenÁa aqui', 'raiva'),
            ('esta comida me parece muito ruim', 'raiva'),
            ('vocÍ me destrÛi', 'raiva'),
            ('estamos separados', 'raiva'),
            ('estou odiando este vestido', 'raiva'),
            ('n„o pude comprar meu celular hoje', 'raiva'),
            ('ela e uma garota ruim', 'raiva'),
            ('estivemos em um show horroroso', 'raiva'),
            ('o ingresso estava muito caro', 'raiva'),
            ('se eu estragar tudo vai por ·gua a baixo', 'raiva'),
            ('n„o possuo dinheiro algum', 'raiva'),
            ('sou muito pobre', 'raiva'),
            ('vai prejudicar a todos esta nova medida', 'raiva'),
            ('ficou ridÌculo', 'raiva'),
            ('este sapato esta muito apertado', 'raiva'),
            ('a musica e uma ofensa aos meus ouvidos', 'raiva'),
            ('n„o consigo terminar uma tarefa muito difÌcil', 'raiva'),
            ('reprovei em minha graduaÁ„o', 'raiva'),
            ('estou muito chateado com tudo', 'raiva'),
            ('eu odeio em vocÍ', 'raiva'),
            ('e um desprazer conhecÍ-lo', 'raiva'),
            ('estou desperdiÁando minhas ferias', 'raiva'),
            ('e muito ruim este jogo', 'raiva'),
            ('vamos ter muito rancor pela frente', 'raiva'),
            ('n„o achei que seria t„o terrÌvel', 'raiva'),
            ('vou vetar o orÁamento ao cliente', 'raiva'),
            ('meus pais n„o consentiram nosso casamento', 'raiva'),
            ('eu odiei este perfume', 'raiva'),
            ('seu descaso e frustrante', 'raiva'),
            ('me sinto completamente amarga', 'raiva'),
            ('desprezo muito o seu trabalho', 'raiva'),
            ('estamos descontentes por nossa famÌlia', 'raiva'),
            ('vou infernizar a sua empresa', 'raiva'),
            ('estou furioso com estes valores', 'raiva'),
            ('obrigaram o rapaz a sair', 'raiva'),
            ('como ele pode deixar de lado?', 'raiva'),
            ('s„o apenas injurias sobre mim', 'raiva'),
            ('estou enfurecido com a situaÁ„o dessa empresa', 'raiva'),
            ('estou com o diabo no corpo', 'raiva'),
            ('isso foi diabÛlico', 'raiva'),
            ('tenho avers„o ‡ gente chata', 'raiva'),
            ('n„o vou perdoar sua traiÁ„o', 'raiva'),
            ('esse dinheiro sujo e corrupto', 'raiva'),
            ('eles me crucificam o tempo todo', 'raiva'),
            ('eu vou enlouquecer com todo este barulho', 'raiva'),
            ('n„o ag¸ento todo esse assedio', 'raiva'),
            ('cÛlera do drag„o', 'raiva'),
            ('isso e ridÌculo!', 'raiva'),
            ('da prÛxima vez, vou inventar tudo sozinho', 'raiva'),
            ('seus tolos! deixaram ele escapar!', 'raiva'),
            ('jamais te perdoarei', 'raiva'),
            ('o que e isso? outra multa', 'raiva'),
            ('vocÍ passou dos limites!', 'raiva'),
            ('sente-se e cale a boca', 'raiva'),
            ('ingratosvermesvocÍs me pagam!', 'raiva'),
            ('saiam da dai, se n„o arranco vocÍs dai!', 'raiva'),
            ('vocÍ j· me causou problemas suficientes', 'raiva'),
            ('isso foi a gota díagua', 'raiva'),
            ('o que vocÍ tem com isso?', 'raiva'),
            ('n„o vejo a hora de me livrar de vocÍ', 'raiva'),
            ('j· entendi a jogada seus safados!', 'raiva'),
            ('vocÍ n„o merece piedade', 'raiva'),
            ('saia de perto de mim', 'raiva'),
            ('suma daqui, ou arranco seu couro!', 'raiva'),
            ('estou revoltado com essa situaÁ„o', 'raiva'),
            ('seu idiota!', 'raiva'),
            ('n„o, eu n„o vou te emprestar dinheiro!', 'raiva'),
            ('vocÍ n„o passa de um cafajeste! vai embora', 'raiva'),
            ('pare de frescura e v· trabalhar', 'raiva'),
            ('eles merecem uma liÁ„o', 'raiva'),
            ('ainda estou muito bravo com vocÍ', 'raiva'),
            ('eu preciso surrar aquela chantagista', 'raiva'),
            ('olha o que vocÍ fez! derramou!', 'raiva'),
            ('vocÍ est· pedindo pra apanhar!', 'raiva'),
            ('me deixa em paz!', 'raiva'),
            ('morra maldito, morra!', 'raiva'),
            ('vocÍ e mais irritante de perto', 'raiva'),
            ('e bom fechar o bico', 'raiva'),

            ('magicamente vocÍ me surpreendeu', 'surpresa'),
            ('e imenso esse globo', 'surpresa'),
            ('isso e tremendamente interessante', 'surpresa'),
            ('meu bilhete for sorteado, inacredit·vel!', 'surpresa'),
            ('um assalto a m„o armada!', 'surpresa'),
            ('incrÌvel, cabe em qualquer lugar!', 'surpresa'),
            ('vocÍ por aqui?', 'surpresa'),
            ('n„o d· pra acreditar no que ela me contou', 'surpresa'),
            ('os convidados j· est„o chegando!', 'surpresa'),
            ('puxa vida! nunca nos livramos de alguem t„o depressa', 'surpresa'),
            ('micha carteira sumiu, eu estava com ela na m„o', 'surpresa'),
            ('oh! um disco voador', 'surpresa'),
            ('amigos, que bela surpresa!', 'surpresa'),
            ('nunca pensei que veria isso e perto', 'surpresa'),
            ('nem acredito que comi tanto', 'surpresa'),
            ('n„o acredito que veio me ver', 'surpresa'),
            ('n„o acredito que e  t„o descarado', 'surpresa'),
            ('me surpreende sua falta de tato', 'surpresa'),
            ('o predio onde eles moravam desabou!', 'surpresa'),
            ('inacredit·vel um bolo t„o grande', 'surpresa'),
            ('e serio mesmo? n„o d· pra acreditar', 'surpresa'),
            ('como assim n„o vai ao nosso encontro?', 'surpresa'),
            ('como assim n„o tem ninguem em casa?', 'surpresa'),
            ('ue, mas para onde ele foi?!', 'surpresa'),
            ('por essa eu n„o esperava', 'surpresa'),
            ('nossa, olha sÛ que mergulho', 'surpresa'),
            ('minha esposa est· gr·vida!', 'surpresa'),
            ('meu dinheiro sumiu!', 'surpresa'),
            ('e verdade que os dois terminaram?!?', 'surpresa'),
            ('caramba, nem vi vocÍ chegar', 'surpresa'),
            ('nossa, como pode alguem cozinhar t„o mal?', 'surpresa'),
            ('nossa que incrÌvel', 'surpresa'),
            ('a fÛrmula sumiu!', 'surpresa'),
            ('eu nem acredito que j· estou terminando o curso', 'surpresa'),
            ('n„o acredito que esta aqui comigo novamente', 'surpresa'),
            ('est· escondendo algo de nÛs!', 'surpresa'),
            ('como assim, ainda n„o terminou a tarefa', 'surpresa'),
            ('pensei que j· estivesse pronta!', 'surpresa'),
            ('opa! quem apagou a luz?', 'surpresa'),
            ('caramba! aonde vai t„o r·pido?', 'surpresa'),
            ('estamos seguindo o caminho errado!', 'surpresa'),
            ('quatro reais o litro da gasolina!', 'surpresa'),
            ('me assustei ao vÍ-lo desse jeito!', 'surpresa'),
            ('minha m„e est· gr·vida, acredita nisso?', 'surpresa'),
            ('parece mentira vocÍ ter crescido tanto', 'surpresa'),
            ('me surpreende sua imaginaÁ„o', 'surpresa'),
            ('suas roupas s„o realmente lindas', 'surpresa'),
            ('com consegue ser t„o bela?', 'surpresa'),
            ('essa e realmente uma casa deslumbrante', 'surpresa'),
            ('superou minhas expectativas', 'surpresa'),
            ('e admir·vel a maneira como se comporta', 'surpresa'),
            ('isso e realmente chocante', 'surpresa'),
            ('algumas noticias me surpreenderam no notici·rio', 'surpresa'),
            ('surpreendente sua festa', 'surpresa'),
            ('estou tremendo de alegria', 'surpresa'),
            ('chocou grande parte do mundo', 'surpresa'),
            ('eu ficaria muito espantado com a sua vinda', 'surpresa'),
            ('ele e admir·vel', 'surpresa'),
            ('sua beleza me surpreendeu', 'surpresa'),
            ('seus olhos s„o surpreendentemente verdes', 'surpresa'),
            ('os polÌticos se surpreendem quando alguem acredita neles', 'surpresa'),
            ('estou perplexa com essas denuncias', 'surpresa'),
            ('fiquei perplexo com suas palavras', 'surpresa'),
            ('estou abismado com sua prosa', 'surpresa'),
            ('eu ficaria realmente abismado se me dissessem isso', 'surpresa'),
            ('o grupo foi surpreendido enquanto lavava o carro', 'surpresa'),
            ('estou boquiaberto com as imagens', 'surpresa'),
            ('estou boquiaberto com essas suas palavras', 'surpresa'),
            ('esse quadro e maravilhoso', 'surpresa'),
            ('este carro me deixou maravilhado', 'surpresa'),
            ('estou maravilhada', 'surpresa'),
            ('essa expectativa esta me matando', 'surpresa'),
            ('vou caminhar sempre na expectativa de encontr·-lo', 'surpresa'),
            ('vocÍ emudece minhas palavras', 'surpresa'),
            ('minhas palavras v„o emudecer se n„o parar de me surpreender', 'surpresa'),
            ('a mulher e um efeito deslumbrante da natureza', 'surpresa'),
            ('estou deslumbrada com essas jÛias', 'surpresa'),
            ('isso e rom‚ntico e deslumbrante', 'surpresa'),
            ('isso pode ser surpreendentemente deslumbrante', 'surpresa'),
            ('trabalho deslumbrante', 'surpresa'),
            ('essas pessoas s„o esplÍndida', 'surpresa'),
            ('e esplendido como o ceu se encontra no momento', 'surpresa'),
            ('e um carro fant·stico', 'surpresa'),
            ('um edifÌcio realmente fant·stico', 'surpresa'),

            ('por favor n„o me abandone', 'tristeza'),
            ('n„o quero ficar sozinha', 'tristeza'),
            ('n„o me deixe sozinha', 'tristeza'),
            ('estou abatida', 'tristeza'),
            ('ele esta todo abatido', 'tristeza'),
            ('t„o triste suas palavras', 'tristeza'),
            ('seu amor n„o e mais meu', 'tristeza'),
            ('estou aborrecida', 'tristeza'),
            ('isso vai me aborrecer', 'tristeza'),
            ('estou com muita afliÁ„o', 'tristeza'),
            ('me aflige o modo como fala', 'tristeza'),
            ('estou em agonia com meu intimo', 'tristeza'),
            ('n„o quero fazer nada', 'tristeza'),
            ('me sinto ansiosa e tensa', 'tristeza'),
            ('n„o consigo parar de chorar', 'tristeza'),
            ('n„o consigo segurar as lagrimas', 'tristeza'),
            ('e muita dor perder um ente querido', 'tristeza'),
            ('estou realmente arrependida', 'tristeza'),
            ('acho que o carma volta, pois agora sou eu quem sofro', 'tristeza'),
            ('vocÍ n„o cumpriu suas promessas', 'tristeza'),
            ('me sinto amargurada', 'tristeza'),
            ('coitado esta t„o triste', 'tristeza'),
            ('j· e tarde de mais', 'tristeza'),
            ('nosso amor acabou', 'tristeza'),
            ('essa noite machuca sÛ para mim', 'tristeza'),
            ('eu n„o estou mais no seu coraÁ„o', 'tristeza'),
            ('vocÍ mudou comigo', 'tristeza'),
            ('quando eu penso em vocÍ realmente dÛi', 'tristeza'),
            ('como se fosse nada vocÍ vÍ minhas lagrimas', 'tristeza'),
            ('vocÍ disse cruelmente que n„o se arrependeu', 'tristeza'),
            ('eu nunca mais vou te ver', 'tristeza'),
            ('ela esta com depress„o', 'tristeza'),
            ('a depress„o aflige as pessoas', 'tristeza'),
            ('estar depressivo e muito ruim', 'tristeza'),
            ('estou derrotada e deprimida depois deste dia', 'tristeza'),
            ('e comovente te ver dessa maneira', 'tristeza'),
            ('e comovente ver o que os filhos do brasil passam', 'tristeza'),
            ('como me sinto culpada', 'tristeza'),
            ('estou abatida', 'tristeza'),
            ('a ansiedade tomou conta de mim', 'tristeza'),
            ('as pessoas n„o gostam do meu jeito', 'tristeza'),
            ('adeus passamos bons momentos juntos', 'tristeza'),
            ('sinto sua falta', 'tristeza'),
            ('ele n„o gostou da minha comida', 'tristeza'),
            ('estou sem dinheiro para a comida', 'tristeza'),
            ('queria que fosse o ultimo dia da minha vida', 'tristeza'),
            ('vocÍ est· com vergonha de mim', 'tristeza'),
            ('ela n„o aceitou a minha proposta', 'tristeza'),
            ('era o meu ultimo centavo', 'tristeza'),
            ('reprovei de ano na faculdade', 'tristeza'),
            ('afinal vocÍ sÛ sabe me desfazer', 'tristeza'),
            ('eu falhei em tudo nessa vida', 'tristeza'),
            ('eu fui muito humilhado', 'tristeza'),
            ('e uma histÛria muito triste', 'tristeza'),
            ('ninguem acredita em mim', 'tristeza'),
            ('eu n„o sirvo para nada mesmo', 'tristeza'),
            ('droga, n„o faÁo nada direito', 'tristeza'),
            ('sofrimento em dobro na minha vida', 'tristeza'),
            ('fui demitida essa semana', 'tristeza'),
            ('as crianÁas sofrem ainda mais que os adultos', 'tristeza'),
            ('pra mim um dia e ruim, o outro e pior', 'tristeza'),
            ('de repente perdi o apetite', 'tristeza'),
            ('oh que dia infeliz', 'tristeza'),
            ('estamos afundados em contas', 'tristeza'),
            ('nem um milagre pode nos salvar', 'tristeza'),
            ('sÛ me resta a esperanÁa', 'tristeza'),
            ('pior que isso n„o pode ficar', 'tristeza'),
            ('meu sal·rio e baixo', 'tristeza'),
            ('n„o passei no vestibular', 'tristeza'),
            ('ninguem se importa comigo', 'tristeza'),
            ('ninguem lembrou do meu anivers·rio', 'tristeza'),
            ('tenho tanto azar', 'tristeza'),
            ('o gosto da vinganÁa e amargo', 'tristeza'),
            ('sou uma mulher amargurada depois de que vocÍ me deixou', 'tristeza'),
            ('estou desanimada com a vida', 'tristeza'),
            ('e um desanimo sÛ coitadinha', 'tristeza'),
            ('a derrota e depressiva', 'tristeza'),
            ('discriminar e desumano', 'tristeza'),
            ('que desanimo', 'tristeza'),
            ('e uma desonra para o pais', 'tristeza'),
            ('a preocupaÁ„o deveria nos levar a aÁ„o n„o a depress„o', 'tristeza'),
            ('passamos ao desalento e a loucura', 'tristeza'),
            ('aquele que nunca viu a tristeza nunca reconhecer· a alegria', 'tristeza'),
            ('cuidado com a tristeza ela e um vicio', 'tristeza')]

        # Base de dados para teste
        baseteste = [
            ('n„o precisei pagar o ingresso', 'alegria'),
            ('se eu ajeitar tudo fica bem', 'alegria'),
            ('minha fortuna ultrapassa a sua', 'alegria'),
            ('sou muito afortunado', 'alegria'),
            ('e benefico para todos esta nova medida', 'alegria'),
            ('ficou lindo', 'alegria'),
            ('achei esse sapato muito simp·tico', 'alegria'),
            ('estou ansiosa pela sua chegada', 'alegria'),
            ('congratulaÁıes pelo seu anivers·rio', 'alegria'),
            ('delicadamente ele a colocou para dormir', 'alegria'),
            ('a musica e linda', 'alegria'),
            ('sem musica eu n„o vivo', 'alegria'),
            ('conclui uma tarefa muito difÌcil', 'alegria'),
            ('conclui minha graduaÁ„o', 'alegria'),
            ('estou muito contente com tudo', 'alegria'),
            ('eu confio em vocÍ', 'alegria'),
            ('e um prazer conhecÍ-lo', 'alegria'),
            ('o coleguismo de vocÍs e animador', 'alegria'),
            ('estou aproveitando as ferias', 'alegria'),
            ('vamos aproveitar as ferias', 'alegria'),
            ('e muito divertido este jogo', 'alegria'),
            ('vamos ter muita divers„o', 'alegria'),
            ('n„o achei que me divertiria tanto assim', 'alegria'),
            ('vou consentir o orÁamento ao cliente', 'alegria'),
            ('com o consentimento dos meus pais podemos nos casar', 'alegria'),
            ('eu adorei este perfume', 'alegria'),
            ('sua bondade e cativante', 'alegria'),
            ('estou despreocupada', 'alegria'),
            ('n„o me preocupo com o que aconteceu', 'alegria'),
            ('me sinto completamente segura', 'alegria'),
            ('estimo muito o seu trabalho', 'alegria'),
            ('somos estimados por nossa famÌlia', 'alegria'),
            ('concretizamos nossa ideia', 'alegria'),
            ('nosso ideal foi alcanÁado', 'alegria'),
            ('estamos muito felizes juntos', 'alegria'),
            ('estou t„o animada com os preparativos para o casamento', 'alegria'),
            ('vocÍ ser· muito amado meu filho', 'alegria'),
            ('os apaixonados s„o maravilhosos', 'alegria'),
            ('agradeÁo imensamente o seu apoio nestes dias', 'alegria'),
            ('esta comida me parece muito atraente', 'alegria'),
            ('vocÍ me completa', 'alegria'),
            ('poderemos completar o projeto hoje!', 'alegria'),
            ('estamos namorando', 'alegria'),
            ('estou namorando este vestido a um tempo', 'alegria'),
            ('pude comprar meu celular hoje', 'alegria'),
            ('e um deleite poder compartilhar minhas vitÛrias', 'alegria'),
            ('ela e um boa garota', 'alegria'),
            ('estivemos em um Ûtimo show', 'alegria'),

            ('o mundo e feio como o pecado', 'desgosto'),
            ('a coisa mais difÌcil de esconder e aquilo que n„o existe', 'desgosto'),
            ('vocÍ errou feio aquele gol', 'desgosto'),
            ('nunca vou me casar sou muito feia', 'desgosto'),
            ('os golpes da adversidade s„o terrivelmente amargos', 'desgosto'),
            ('os homem ficam terrivelmente chatos', 'desgosto'),
            ('abominavelmente convencido', 'desgosto'),
            ('terrivelmente irritado', 'desgosto'),
            ('as instituiÁıes publicas est„o terrivelmente decadentes', 'desgosto'),
            ('a populaÁ„o viveu em isolamento por muito tempo', 'desgosto'),
            ('estou terrivelmente preocupada', 'desgosto'),
            ('o nacionalismo e uma doenÁa infantil', 'desgosto'),
            ('se me es antip·tico a minha negaÁ„o esta pronta', 'desgosto'),
            ('muitos document·rios sobre esse casal antip·tico', 'desgosto'),
            ('sua beleza n„o desfaÁa sua antipatia', 'desgosto'),
            ('esta e uma experiÍncia desagrad·vel', 'desgosto'),
            ('desagrad·vel estrago nos banheiros', 'desgosto'),
            ('o mais irritante no amor e que se trata de um crime que precisa de um c˙mplice', 'desgosto'),
            ('a situaÁ„o nos causa grande incomodo', 'desgosto'),
            ('estou preocupado com o incomodo na garganta', 'desgosto'),
            ('simplesmente n„o quero amolaÁ„o da policia', 'desgosto'),
            ('vocÍ e uma criaturinha muito impertinente', 'desgosto'),
            ('o peso e a dor da vida', 'desgosto'),
            ('me arrependo amargamente de minhas aÁıes', 'desgosto'),
            ('o destino e cruel e os homens n„o s„o dignos de compaix„o', 'desgosto'),
            ('o Ûdio conduz ao isolamento cruel e ao desespero', 'desgosto'),
            ('encerrou com o massacre mais repudi·vel e asqueroso que se conhece', 'desgosto'),
            ('de mal gosto e asqueroso', 'desgosto'),
            ('tudo e inserto neste mundo hediondo', 'desgosto'),
            ('o crime de corrupÁ„o e um crime hediondo', 'desgosto'),
            ('o rio esta fetido e de cor escura', 'desgosto'),
            ('muito lixo no rio o deixa malcheiroso', 'desgosto'),
            ('existe uma laranja podre no grupo e j· desconfiamos quem e', 'desgosto'),
            ('foi de repente estou machucado e me sentindo enjoado', 'desgosto'),
            ('eu fiquei enojado', 'desgosto'),
            ('daqui alguns meses vou embora deste pais que j· estou nauseado', 'desgosto'),

            ('que abomin·vel esse montro!', 'medo'),
            ('vamos alarmar a todos sobre a situaÁ„o', 'medo'),
            ('estou amedrontada', 'medo'),
            ('estou com muito medo da noite', 'medo'),
            ('ele esta me ameaÁando a dias', 'medo'),
            ('quanta angustia', 'medo'),
            ('estou angustiada', 'medo'),
            ('angustiadamente vou sair e casa', 'medo'),
            ('isso me deixa apavorada', 'medo'),
            ('vocÍ esta me apavorando', 'medo'),
            ('estou desconfiada de vocÍ', 'medo'),
            ('n„o confio em vocÍ', 'medo'),
            ('ate o cachorro est· apavorado', 'medo'),
            ('estou assustado com as aÁıes do meu colega', 'medo'),
            ('agora se sente humilhado, apavorado', 'medo'),
            ('assustou a populaÁ„o e provocou mortes', 'medo'),
            ('estou com dificuldades para respirar e muito assustado', 'medo'),
            ('os policiais se assustaram quando o carro capotou', 'medo'),
            ('o trabalhador e assombrado pelo temor do desemprego', 'medo'),
            ('este lugar e mal assombrado', 'medo'),
            ('estou assombrado pela crise financeira', 'medo'),
            ('mesmo aterrorizado lembro de vocÍ', 'medo'),
            ('aterrorizado e suando frio', 'medo'),
            ('um grupo de elefantes selvagens tem aterrorizado vilas', 'medo'),
            ('me sinto intimidada pela sua presenÁa', 'medo'),
            ('tenho medo de ser advertida novamente', 'medo'),
            ('estou correndo o risco de ser advertido', 'medo'),
            ('estou correndo riscos de sa˙de', 'medo'),
            ('os riscos s„o reais', 'medo'),
            ('podemos perder muito dinheiro com essa investida', 'medo'),
            ('socorro, fui intimado a depor', 'medo'),
            ('fui notificado e estou com medo de perde a guarda da minha filha', 'medo'),
            ('estou angustiada com meus filhos na rua', 'medo'),
            ('e abomin·vel o que fazem com os animais', 'medo'),
            ('foi terrÌvel o tigre quase o matou', 'medo'),
            ('me advertiram sobre isso', 'medo'),

            ('ate que enfim, n„o ag¸entava mais te esperar', 'raiva'),
            ('eu quero meu dinheiro de volta agora!', 'raiva'),
            ('eu odeio a escola!', 'raiva'),
            ('vou fazer picadinho de vocÍ', 'raiva'),
            ('detesto trabalhar no ver„o', 'raiva'),
            ('quero minha comida, e quero agora!', 'raiva'),
            ('melhor vocÍ recolher minhas compras agora!', 'raiva'),
            ('quero descer agora sua maluca', 'raiva'),
            ('vou reclamar com o gerente!', 'raiva'),
            ('vai engolir o que disse!', 'raiva'),
            ('ele me ridiculariza diante de todos', 'raiva'),
            ('n„o quero mais saber de vocÍ', 'raiva'),
            ('vejo vocÍ na cadeia safado!', 'raiva'),
            ('agora vou ter que pagar mais isso ainda!', 'raiva'),
            ('saia logo do banheiro!', 'raiva'),
            ('suba j· para o seu quarto!', 'raiva'),
            ('eu falei para calar a boca seu idiota!', 'raiva'),
            ('eu disse para vocÍ cair fora!', 'raiva'),
            ('n„o ag¸ento mais que fiquem me culpando sem motivo!', 'raiva'),
            ('n„o suporto olhar na sua cara!', 'raiva'),
            ('eu n„o sou um elefante', 'raiva'),
            ('juro que se olhar pra mim eu o mato!', 'raiva'),
            ('chega, n„o quero saber mais deste assunto', 'raiva'),
            ('como pode ser t„o burro?', 'raiva'),
            ('n„o me aborreÁa seu moleque', 'raiva'),
            ('n„o quero me aborrecer com estas bobagens', 'raiva'),
            ('ele me agrediu!', 'raiva'),
            ('eu amaldiÁÙo vocÍ e a sua famÌlia', 'raiva'),
            ('n„o me amole', 'raiva'),
            ('n„o venha me amolar', 'raiva'),
            ('isso tudo e uma tormenta', 'raiva'),
            ('eu vou matar vocÍ', 'raiva'),
            ('para que simplificar se vocÍ pode sempre complicar', 'raiva'),
            ('isso esta me enlouquecendo', 'raiva'),
            ('estou furiosa com vocÍ', 'raiva'),
            ('isso mesmo fique furioso', 'raiva'),

            ('esses livros s„o magnÌficos', 'surpresa'),
            ('esse vinho e magnÌfico', 'surpresa'),
            ('seria magnÌfico ver o esperaculo', 'surpresa'),
            ('o casamento foi estupendo', 'surpresa'),
            ('e um jogador b·rbaro estupendo', 'surpresa'),
            ('esse dia esta excelente', 'surpresa'),
            ('o cantor estava excelente', 'surpresa'),
            ('o universo e assombroso', 'surpresa'),
            ('o amor e sublime', 'surpresa'),
            ('sua sublime atuaÁ„o', 'surpresa'),
            ('e formid·vel meu caro walter', 'surpresa'),
            ('como e formid·vel a presenÁa de todos', 'surpresa'),
            ('e formid·vel ter a quem dizer adeus', 'surpresa'),
            ('e um conselheiro formid·vel o seu', 'surpresa'),
            ('o artigo foi formid·vel', 'surpresa'),
            ('pica pau e um destaque no imagin·rio brasileiro', 'surpresa'),
            ('ah! o absoluto do imagin·rio', 'surpresa'),
            ('isso foi surreal', 'surpresa'),
            ('uma historia completamente surreal', 'surpresa'),
            ('essas pinturas beiram o surreal', 'surpresa'),
            ('vocÍ nem acreditam de t„o surreal', 'surpresa'),
            ('incrÌvel!', 'surpresa'),
            ('fiquei pasma com tudo isso', 'surpresa'),
            ('vocÍ me deixa pasmo', 'surpresa'),
            ('estou admirado com a sua astucia', 'surpresa'),
            ('que bela surpresa vocÍ me fez', 'surpresa'),
            ('n„o acredito que fez isso!', 'surpresa'),
            ('isso foi apavorante', 'surpresa'),
            ('isso t„o de repente', 'surpresa'),
            ('estou chocada com isso', 'surpresa'),
            ('estou surpresa e desconsertada', 'surpresa'),
            ('esta realmente deslumbrante querida', 'surpresa'),
            ('fiquei completamente sem plavras', 'surpresa'),
            ('e espantoso o modo como ele nos olha', 'surpresa'),
            ('incrivel vocÍ estar aqui', 'surpresa'),
            ('que fant·stica festa minha querida', 'surpresa'),

            ('isso tudo e um erro', 'tristeza'),
            ('eu sou errada eu sou errante', 'tristeza'),
            ('tenho muito dÛ do cachorro', 'tristeza'),
            ('e dolorida a perda de um filho', 'tristeza'),
            ('essa tragedia vai nos abalar para sempre', 'tristeza'),
            ('perdi meus filhos', 'tristeza'),
            ('perdi meu curso', 'tristeza'),
            ('sou sÛ uma chorona', 'tristeza'),
            ('vocÍ e um chor„o', 'tristeza'),
            ('se arrependimento matasse', 'tristeza'),
            ('me sinto deslocado em sala de aula', 'tristeza'),
            ('foi uma passagem f˙nebre', 'tristeza'),
            ('nossa condolÍncias e tristeza a sua perda', 'tristeza'),
            ('desanimo, raiva, solid„o ou vazies, depress„o', 'tristeza'),
            ('vivo te desanimando', 'tristeza'),
            ('estou desanimado', 'tristeza'),
            ('imperador sanguin·rio, depravado e temeroso', 'tristeza'),
            ('meu ser esta em agonia', 'tristeza'),
            ('este atrito entre nos tem que acabar', 'tristeza'),
            ('a escurid„o desola meu ser', 'tristeza'),
            ('sua falsa preocupaÁ„o', 'tristeza'),
            ('sua falsidade me entristece', 'tristeza'),
            ('quem esta descontente com os outros esta descontente consigo prÛprio', 'tristeza'),
            ('a torcida esta descontente com a demiss„o do tecnico', 'tristeza'),
            ('estou bastante aborrecido com o jornal', 'tristeza'),
            ('me sinto solit·rio e entediado', 'tristeza'),
            ('a vida e solit·ria para aqueles que n„o s„o falsos', 'tristeza'),
            ('como com compuls„o depois da depress„o', 'tristeza'),
            ('estou me desencorajando a viver', 'tristeza'),
            ('ele desencoraja minhas vontades', 'tristeza'),
            ('isso vai deprimindo por dentro', 'tristeza'),
            ('acho que isso e defeituoso', 'tristeza'),
            ('os remedios me derrubam na cama', 'tristeza'),
            ('a depress„o vai me derrubar', 'tristeza'),
            ('suas desculpas s„o falsas', 'tristeza'),
            ('n„o magoe as pessoas', 'tristeza')]

        # Configurando stopwords para portugues
        stopWordsNltk = nltk.corpus.stopwords.words('portuguese')

        # Pré processamento das frases

        '''
        REMOVENDO STOPWORDS
        Stop words são as palavras irrelevantes para os testes e serão
        removidas usando o padrão do nltk
        '''
        def eliminaStopWords(texto):
            frases = []
            for (palavras, emocao) in texto:
                semStop = [p for p in palavras.split()
                           if p not in stopWordsNltk]
                frases.append((semStop, emocao))
            return frases
        eliminaStopWords(basetreinamento)

        '''
        REMOVENDO STEMMING
        Esse parte irá remover o radical das palavras. Esse RSLPStemmer
        é usado especificamente para remover o stemming em portugues
        '''
        def apllicaStemmer(texto):
            stemmer = nltk.stem.RSLPStemmer()
            frasesSteemming = []
            for (palavras, emocao) in texto:
                comStemming = [str(stemmer.stem(p))
                               for p in palavras.split() if p not in stopWordsNltk]
                frasesSteemming.append((comStemming, emocao))
            return frasesSteemming

        frasesComStemming = apllicaStemmer(basetreinamento)

        '''
        BUSCA PALAVRAS
        Essa função busca todas as palavras da base de dados
        '''
        def buscapalavras(frases):
            todasPalavras = []
            for (palavras, emocao) in frases:
                todasPalavras.extend(palavras)
            return todasPalavras

        palavras = buscapalavras(frasesComStemming)

        '''
        BUSCA FREQUENCIA
        Esse método irá buscar a frequencia de cada palavra
        '''
        def buscaFrequencia(palavras):
            palavras = nltk.FreqDist(palavras)
            return palavras

        frequencia = buscaFrequencia(palavras)
        frequencia.most_common(50)

        '''
        BUSCA PALAVRAS UNICAS
        Esse método irá buscar a frequencia de cada palavra única
        '''
        def buscarPalavrasUnicas(frequencia):
            # Pegando palavras nao repetidas
            freq = frequencia.keys()
            return freq

        palavrasUnicas = buscarPalavrasUnicas(frequencia)

        '''
        EXTRATOR DE PALAVRAS
        Recebe um determinado documento e verifica se esta palvra existe
        ou não neste determinado documento
        '''
        def extratorPalavras(documento):
            doc = set(documento)
            caracteristicas = {}
            for palavras in palavrasUnicas:
                caracteristicas['%s' % palavras] = (palavras in doc)
            return caracteristicas

        '''
        Vamos chamar o metodo apply_features do nltk passando como parametro 
        o extratorPalavras e como segundo parametro o frasesComStemming para 
        termos a nossa base final e já treinada
        '''
        basecompleta = nltk.classify.apply_features(
            extratorPalavras, frasesComStemming)

        #Detectando emoções em textos com nltk
        classificador = nltk.NaiveBayesClassifier.train(basecompleta)
        entrada = avaliacao
        testestemming = []
        stemmer = nltk.stem.RSLPStemmer()
        for(palavras) in entrada.split():
            comstem = [p for p in palavras.split()]
            testestemming.append(str(stemmer.stem(comstem[0])))

        novo = extratorPalavras(testestemming)
        resultado = classificador.classify(novo)
        return resultado
